#!/bin/bash

drush en ictdirecta_torulethemall

drush fr ictdirecta_xhemeroteca 

echo "EL MODULO UUID_FEATURES NO CHUTA VIA DRUSH!! SE HA DE ACTIVAR POR INTERFICIE DESPUES DE ESTE SCRIPT"
echo "EL MODULO UUID_FEATURES NO CHUTA VIA DRUSH!! SE HA DE ACTIVAR POR INTERFICIE DESPUES DE ESTE SCRIPT"
echo "EL MODULO UUID_FEATURES NO CHUTA VIA DRUSH!! SE HA DE ACTIVAR POR INTERFICIE DESPUES DE ESTE SCRIPT"
