#!/bin/bash

drush en ictdirecta_torulethemallnew

drush fr ictdirecta_xhemeroteca 

drush dis uuid_features

drush en ictdirecta_torulethemallnew

echo "EL MODULO UUID_FEATURES NO CHUTA VIA DRUSH!! SE HA DE ACTIVAR POR INTERFICIE DESPUES DE ESTE SCRIPT"
echo "EL MODULO UUID_FEATURES NO CHUTA VIA DRUSH!! SE HA DE ACTIVAR POR INTERFICIE DESPUES DE ESTE SCRIPT"
echo "EL MODULO UUID_FEATURES NO CHUTA VIA DRUSH!! SE HA DE ACTIVAR POR INTERFICIE DESPUES DE ESTE SCRIPT"
