<?
/**
 * Implements hook_block_info().
 */
function directa_custom_block_info() {
  return array(
    'openx_banner_lateralgran1' => array(
      'info' => t('Banner OpenX: Lateral gran 1 300x500'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'openx_banner_lateralpetit1' => array(
      'info' => t('Banner OpenX: Lateral petit 1 300x150'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'openx_banner_lateralpetit2' => array(
      'info' => t('Banner OpenX: Lateral petit 2 300x150'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'openx_banner_lateralpetit3' => array(
      'info' => t('Banner OpenX: Lateral petit 3 300x150'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'openx_banner_lateralpetit4' => array(
      'info' => t('Banner OpenX: Lateral petit 4 300x150 - sota impressions'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'seccions_portada' => array(
      'info' => t('Mes noticies per 5 seccions'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'mes_noticies' => array(
      'info' => t('Mes noticies node final'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'comptador_subscriptores' => array(
      'info' => t('Comptador de Subscriptores'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function directa_custom_block_view($delta = '') {
  $block = array();
  switch($delta) {
  case 'openx_banner_lateralgran1':
    $block['subject'] = '';
    $block['content'] = <<<EOF
      <script type='text/javascript'>
         var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
         var m3_r = Math.floor(Math.random()*99999999999);
         if (!document.MAX_used) document.MAX_used = ',';
         document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
         document.write ("?zoneid=8");
         document.write ('&amp;cb=' + m3_r);
         if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
         document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
         document.write ("&amp;loc=" + escape(window.location));
         if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
         if (document.context) document.write ("&context=" + escape(document.context));
         if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
         document.write ("'><\/scr"+"ipt>");</script>
         <noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=af0c3878&amp;cb=092340230' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=8&amp;cb=84848345&amp;n=af0c3878' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'openx_banner_lateralpetit1':
    $block['subject'] = '';
    $block['content'] = <<<EOF
<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=9");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=a84e5d32&amp;cb=784278942' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=9&amp;cb=9842942&amp;n=a84e5d32' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'openx_banner_lateralpetit2':
    $block['subject'] = '';
    $block['content'] = <<<EOF
<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=10");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=a3068645&amp;cb=87245' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=10&amp;cb=983247&amp;n=a3068645' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'openx_banner_lateralpetit3':
    $block['subject'] = '';
    $block['content'] = <<<EOF
<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=11");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=ae2b992a&amp;cb=274849' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=11&amp;cb=437894334&amp;n=ae2b992a' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'openx_banner_lateralpetit4':
    $block['subject'] = '';
    $block['content'] = <<<EOF
<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=12");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=aadc1b0e&amp;cb=434343' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=12&amp;cb=4433434&amp;n=aadc1b0e' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'seccions_portada':
    // carreguem els nid que no shan de mostrar a les views de seccions
    $col_esq   = views_get_view_result('portada_columnaizquierda', 'block_1');
    $col_dreta = views_get_view_result('portada_columnadreta', 'block_1');
    $col_dest  = views_get_view_result('portada_destacadotodascolumnas', 'block');
    $results   = array_merge($col_esq, $col_dreta, $col_dest);
    $exclude_nid = '';
    foreach($results as $id => $node) {
      if($exclude_nid != '') {
        $exclude_nid .= ',';
      }
      $exclude_nid .= $node->nid;
    }
    $block['subject'] = '';
    $block['content'] = views_embed_view('portada_seccions', 'block', $exclude_nid);
    $block['content'] .= views_embed_view('portada_seccions', 'block_1', $exclude_nid);
    $block['content'] .= views_embed_view('portada_seccions', 'block_2', $exclude_nid);
    $block['content'] .= views_embed_view('portada_seccions', 'block_3', $exclude_nid);
    $block['content'] .= views_embed_view('portada_seccions', 'block_4', $exclude_nid);
    $block['content'] .= views_embed_view('portada_seccions', 'block_5', $exclude_nid);

    break;

  case 'mes_noticies':
    global $node;
    if ( arg(0) == 'node' && is_numeric(arg(1)) && ! arg(2) ) {
      $node = node_load(arg(1));
      $block['subject'] = t('Més noticies');
      $block['content'] = views_embed_view('ultimes_noticies', 'block_1', $node->nid, $node->field_seccio_web[LANGUAGE_NONE][0]['tid']);
    }
    break;

  case 'comptador_subscriptores':
    $block['subject'] = '';
    /***
     * TODO aixo sha de fer mes eficient!
     */
    /** carreguem tots els usuaris en un array, nomes uid**/
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'user')
      ->addMetaData('account', user_load(1));
    $results = $query->execute();
    /** reorrem el array user a user **/
    $total_subscrites = 0;
    foreach($results['user'] as $key => $user) {
      /** carreguem tot lusuari i mirem si te el rol 8, subscripcio activa**/
      if(array_key_exists('8', user_load($key)->roles)) {
        $total_subscrites++;
      }
    }
    $block['content'] = 'Som <span class="comptador">' . $total_subscrites . '</span> subscriptores. <div class="subs">Faltes tu!</div>';
    break;

  }
  return $block;
}

/**
 * Implements hook_form_alter().
 * Implementation of hook_form_profile2_edif_PROFILE_NAME_form_alter()
 */
function directa_custom_form_profile2_edit_main_form_alter(&$form, &$form_state) {
  // carregeum la taxonomia i els seus termes
  $v = taxonomy_vocabulary_machine_name_load('plantilles_mail_subscripcions');
  $terms = taxonomy_get_tree($v->vid);
  // preperem la concatenacio de contingut
  $output = "<label>Plantilles</label>";
  $output .= '<div id="plantilles-wrapper">';
  foreach($terms as $count => $term) {
    $output .= '<div class="plantilla-wrapper '. $count . '">';
    $output .= '  <div class="plantilla-title">' . $term->name . '</div>';
    $output .= '  <div class="plantilla-cont" >' . $term->description . '</div>';
    $output .= "</div>";
  }
  $output .= "</div>";

  // ho afegim a sota del email body
  $form['profile_main']['field_email_body'][LANGUAGE_NONE]['#suffix'] .= $output;

  // carreguem el js a mida
  drupal_add_js(drupal_get_path('module', 'directa_custom') . '/js/custom_user_profile_edit.js');

  // afegim la nostra funcio de submit
  $form['#submit'][] = 'directa_custom_user_submit';
}

function directa_custom_user_submit($form, &$form_state) {
  // si esta marcat enviar mail procedim
  if($form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] != NULL) {
    // creem el missatge a guardar
    $register = 'Correu electrònic enviat:' . "\n";
    $register .= $form_state['values']['profile_main']['field_email_subject'][LANGUAGE_NONE][0]['value'] . "\n\n";
    $register .= $form_state['values']['profile_main']['field_email_body'][LANGUAGE_NONE][0]['value'];
    // el posem en el primer element buit, per si existeix
    foreach($form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE] as $id => $item) {
      if($item['value'] == '') {
        $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id]['value'] = $register;
        $form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] = NULL;
        break;
      }
    }
    // si no existeix (tots plens) el creem
    if($form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] != NULL) {
      $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id+1] = array();
      $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id+1]['value'] = $register;
      $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id+1]['_weight'] = $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id]['_weight'] + 1;
      $form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] = NULL;
    }

    $params = array();
    $params['body'] = "adsf";
    $params['context'] = array();
    $language = language_default();
    $params = array(
      '@url' => url('node/'),
      '@title' => 'asdf',
    );
    $msg = drupal_mail('directa_custom', 'test', 'juli@projecteictineo.com', $language, $params, 'test@examplesdo.com', true);
    //dsm($msg);

  // borrem el congingut
  $form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] = NULL;
    $form_state['values']['profile_main']['field_email_subject'][LANGUAGE_NONE][0]['value'] = '';
    $form_state['values']['profile_main']['field_email_body'][LANGUAGE_NONE][0]['value'] = '';
  }
}

function directa_custom_mail($key, &$message, $params) {
    $message['subject'] = t("@title event registration confirmation", $params);
    $message['body'] = array();
    $message['body'][] = t("Hello", $params);
    $message['body'][] = t("Node has been created @title (@url).", $params);
}


?>
