<?php

/**
 * implementation hook_node_access()
 * Limit access to node pages bases on nodetype
 * @param unknown_type $node
 * @param unknown_type $op
 * @param unknown_type $account
 *
 * Usat per l'embargament compara flag del contingut amb rol d'usuari per fer un 403
 */
function directa_custom_node_access($node, $op, $account) { 
  if (! is_object($node)) {
    return NODE_ACCESS_IGNORE;
  }
  
  $type = is_string($node) ? $node : $node->type;

  if($op == 'view' && arg(0) == 'node' && arg(1) === $node->nid && ($type == 'numero_paper' || $type == 'noticia_paper')) {
    $flag = flag_get_flag('embargament');
    if($flag->is_flagged($node->nid) && (array_key_exists(1, $account->roles) || array_key_exists(9, $account->roles))) {
      return NODE_ACCESS_DENY;
    }
  }

  // Returning nothing from this function would have the same effect.
  return NODE_ACCESS_IGNORE;
}

function directa_custom_menu() {
  $menu['admin/config/directa'] = array (
    'title' => t('La Directa'),
    'description' => t('Configuracions a mida per La Directa'),
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer faldo'),                                                                   
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $menu['admin/config/directa/faldo'] = array (
    'title' => t('Configuració del faldó'),
    'description' => t('Activar / desactivar el faldó per tot el site'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('directa_custom_enable_faldo'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer faldo'),                                                                   
  );
  return $menu;
}

function directa_custom_enable_faldo() {
  $form = array();
  $form['directa_custom_enable_faldo'] = array( 
    '#type' => 'radios',
    '#options' => array(0 => "Ocultar", 1 => "Mostrar"),
    '#title' => 'Faldó de número en paper:',
    '#default_value' => variable_get('directa_custom_enable_faldo', ''),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_permision().
 */
function directa_custom_permission() {
  return array(
    'administer faldo' => array(
      'title' => t('Administra el faldó'),
      'description' => t('activar/desactivar el faldó de nou numero en paper'),
    ),
  );
}


/**
 * Implements hook_form_alter().
 * Implementation of hook_form_profile2_edif_PROFILE_NAME_form_alter()
 */
function directa_custom_form_profile2_edit_main_form_alter(&$form, &$form_state) {
  // carregeum la taxonomia i els seus termes
  $v = taxonomy_vocabulary_machine_name_load('plantilles_mail_subscripcions');
  $terms = taxonomy_get_tree($v->vid);
  // preperem la concatenacio de contingut
  $output = "<label>Plantilles</label>";
  $output .= '<div id="plantilles-wrapper">';
  foreach($terms as $count => $term) {
    $output .= '<div class="plantilla-wrapper '. $count . '">';
    $output .= '  <div class="plantilla-title">' . $term->name . '</div>';
    $output .= '  <div class="plantilla-cont" >' . $term->description . '</div>';
    $output .= "</div>";
  }
  $output .= "</div>";

  // ho afegim a sota del email body
  $form['profile_main']['field_email_body'][LANGUAGE_NONE]['#suffix'] .= $output;

  // carreguem el js a mida
  drupal_add_js(drupal_get_path('module', 'directa_custom') . '/js/custom_user_profile_edit.js');

  // afegim la nostra funcio de submit
  $form['#submit'][] = 'directa_custom_user_submit';
}

function directa_custom_user_submit($form, &$form_state) {
  // si esta marcat enviar mail procedim
  if($form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] != NULL) {
    // creem el missatge a guardar
    $register = 'Correu electrònic enviat:' . "\n";
    $register .= $form_state['values']['profile_main']['field_email_subject'][LANGUAGE_NONE][0]['value'] . "\n\n";
    $register .= $form_state['values']['profile_main']['field_email_body'][LANGUAGE_NONE][0]['value'];
    // el posem en el primer element buit, per si existeix
    foreach($form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE] as $id => $item) {
      if($item['value'] == '') {
        $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id]['value'] = $register;
        $form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] = NULL;
        break;
      }
    }
    // si no existeix (tots plens) el creem
    if($form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] != NULL) {
      $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id+1] = array();
      $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id+1]['value'] = $register;
      $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id+1]['_weight'] = $form_state['values']['profile_main']['field_missatge'][LANGUAGE_NONE][$id]['_weight'] + 1;
      $form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] = NULL;
    }

    $params = array();
    $params['body'] = "adsf";
    $params['context'] = array();
    $language = language_default();
    $params = array(
      '@url' => url('node/'),
      '@title' => 'asdf',
    );
    $msg = drupal_mail('directa_custom', 'test', 'juli@projecteictineo.com', $language, $params, 'test@examplesdo.com', true);
    //dsm($msg);

  // borrem el congingut
  $form_state['values']['profile_main']['field_email'][LANGUAGE_NONE][0]['value'] = NULL;
    $form_state['values']['profile_main']['field_email_subject'][LANGUAGE_NONE][0]['value'] = '';
    $form_state['values']['profile_main']['field_email_body'][LANGUAGE_NONE][0]['value'] = '';
  }
}

function directa_custom_mail($key, &$message, $params) {
    $message['subject'] = t("@title event registration confirmation", $params);
    $message['body'] = array();
    $message['body'][] = t("Hello", $params);
    $message['body'][] = t("Node has been created @title (@url).", $params);
}

function directa_form_alter(&$form, &$form_state, $form_id){
  if($form_id =="views_exposed_form"){
    if($form['#id'] ==  "views-exposed-form-hemeroteca-page") {
      // print $form array on the top of the page
      if (isset($form['search_api_views_fulltext'])) {
           $form['search_api_views_fulltext']['#attributes'] = array('placeholder' => array(t('Escriu la teva recerca')));
      }
      if (isset($form['field_seccio'])) {
           $form['field_seccio']['#attributes'] = array('placeholder' => array(t('Escull seccions')));
      }  
      if (isset($form['field_etiquetes'])) {
           $form['field_etiquetes']['#attributes'] = array('placeholder' => array(t('Etiquetes')));
      }  
      if (isset($form['author'])) {
           $form['author']['#attributes'] = array('placeholder' => array(t('Escull autor')));
      }  
      $form['submit']['#value'] = t('Adequar la recerca');
      //$form = array('field_data_w' => array(
        //'#type' => 'fieldset',
      //)) + $form;
      //$form['field_data_w']['field_data'] = $form['field_data'];
      //$form['field_data_w']['field_data_1'] = $form['field_data_1'];
      //unset($form['field_data']);
      //unset($form['field_data_1']);
    }
  }
}

/**
 * Implements hook_block_info().
 */
function directa_custom_block_info() {
  return array(
    'openx_banner_lateralgran1' => array(
      'info' => t('Banner OpenX: Lateral gran 1 300x500'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'openx_banner_lateralpetit1' => array(
      'info' => t('Banner OpenX: Lateral petit 1 300x150'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'openx_banner_lateralpetit2' => array(
      'info' => t('Banner OpenX: Lateral petit 2 300x150'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'openx_banner_lateralpetit3' => array(
      'info' => t('Banner OpenX: Lateral petit 3 300x150'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'openx_banner_lateralpetit4' => array(
      'info' => t('Banner OpenX: Lateral petit 4 300x150 - sota impressions'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'seccions_portada' => array(
      'info' => t('Mes noticies per 5 seccions'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'mes_noticies' => array(
      'info' => t('Mes noticies node final'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
    'comptador_subscriptores' => array(
      'info' => t('Comptador de Subscriptores'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function directa_custom_block_view($delta = '') {
  $block = array();
  switch($delta) {
  case 'openx_banner_lateralgran1':
    drupal_add_js('http://directa.cat/openx/www/delivery/spcjs.php?id=1&amp;block=1&amp;blockcampaign=1', 'external');
    $block['subject'] = '';
    $block['content'] = "<script type='text/javascript'> OA_show(8); </script>";
    break;

  case 'openx_banner_lateralpetit1':
    $block['subject'] = '';
    $block['content'] = <<<EOF
<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=9");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=a84e5d32&amp;cb=784278942' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=9&amp;cb=9842942&amp;n=a84e5d32' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'openx_banner_lateralpetit2':
    $block['subject'] = '';
    $block['content'] = <<<EOF
<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=10");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=a3068645&amp;cb=87245' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=10&amp;cb=983247&amp;n=a3068645' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'openx_banner_lateralpetit3':
    $block['subject'] = '';
    $block['content'] = <<<EOF
<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=11");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=ae2b992a&amp;cb=274849' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=11&amp;cb=437894334&amp;n=ae2b992a' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'openx_banner_lateralpetit4':
    $block['subject'] = '';
    $block['content'] = <<<EOF
<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://directa.cat/openx/www/delivery/ajs.php':'http://directa.cat/openx/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=12");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://directa.cat/openx/www/delivery/ck.php?n=aadc1b0e&amp;cb=434343' target='_blank'><img src='http://directa.cat/openx/www/delivery/avw.php?zoneid=12&amp;cb=4433434&amp;n=aadc1b0e' border='0' alt='' /></a></noscript>
EOF;
    break;

  case 'seccions_portada':
    // carreguem els nid que no shan de mostrar a les views de seccions
    $col_esq   = views_get_view_result('portada_columnaizquierda', 'block_1');
    $col_dreta = views_get_view_result('portada_columnadreta', 'block_1');
    $col_dest  = views_get_view_result('portada_destacadotodascolumnas', 'block');
    $results   = array_merge($col_esq, $col_dreta, $col_dest);
    $exclude_nid = '';
    foreach($results as $id => $node) {
      if($exclude_nid != '') {
        $exclude_nid .= ',';
      }
      $exclude_nid .= $node->nid;
    }
    $block['subject'] = '';
    $wrapped_section  = '<div id="seccio1-wrapper">';
    $wrapped_section .=   views_embed_view('portada_seccions', 'block', $exclude_nid);
    $wrapped_section .=   views_embed_view('clon_de_portada_seccions_llistat_', 'block', $exclude_nid);
    $wrapped_section .= '</div>';
    $block['content'] = $wrapped_section;

    $wrapped_section  = '<div id="seccio1-wrapper">';
    $wrapped_section .=   views_embed_view('portada_seccions', 'block_1', $exclude_nid);
    $wrapped_section .=   views_embed_view('clon_de_portada_seccions_llistat_', 'block_1', $exclude_nid);
    $wrapped_section .= '</div>';
    $block['content'] .= $wrapped_section;

    $wrapped_section  = '<div id="seccio1-wrapper">';
    $wrapped_section .=   views_embed_view('portada_seccions', 'block_2', $exclude_nid);
    $wrapped_section .=   views_embed_view('clon_de_portada_seccions_llistat_', 'block_2', $exclude_nid);
    $wrapped_section .= '</div>';
    $block['content'] .= $wrapped_section;

    $wrapped_section  = '<div id="seccio1-wrapper">';
    $wrapped_section .=   views_embed_view('portada_seccions', 'block_3', $exclude_nid);
    $wrapped_section .=   views_embed_view('clon_de_portada_seccions_llistat_', 'block_3', $exclude_nid);
    $wrapped_section .= '</div>';
    $block['content'] .= $wrapped_section;

    $wrapped_section  = '<div id="seccio1-wrapper">';
    $wrapped_section .=   views_embed_view('portada_seccions', 'block_4', $exclude_nid);
    $wrapped_section .=   views_embed_view('clon_de_portada_seccions_llistat_', 'block_4', $exclude_nid);
    $wrapped_section .= '</div>';
    $block['content'] .= $wrapped_section;

    $wrapped_section  = '<div id="seccio1-wrapper">';
    $wrapped_section .=   views_embed_view('portada_seccions', 'block_5', $exclude_nid);
    $wrapped_section .=   views_embed_view('clon_de_portada_seccions_llistat_', 'block_5', $exclude_nid);
    $wrapped_section .= '</div>';
    $block['content'] .= $wrapped_section;

    break;

  case 'mes_noticies':
    global $node;
    if ( arg(0) == 'node' && is_numeric(arg(1)) && ! arg(2) ) {
      $node = node_load(arg(1));
      $block['subject'] = t('Més noticies');
      $block['content'] = views_embed_view('ultimes_noticies', 'block_1', $node->nid, $node->field_seccio_web[LANGUAGE_NONE][0]['tid']);
    }
    break;

  case 'comptador_subscriptores':
    $block['subject'] = '';
    /***
     * TODO aixo sha de fer mes eficient!
     */
    /** carreguem tots els usuaris en un array, nomes uid**/
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'user')
      ->addMetaData('account', user_load(1));
    $results = $query->execute();
    /** reorrem el array user a user **/
    $total_subscrites = 0;
    foreach($results['user'] as $key => $user) {
      /** carreguem tot lusuari i mirem si te el rol 8, subscripcio activa**/
      if(array_key_exists('8', user_load($key)->roles)) {
        $total_subscrites++;
      }
    }
    $block['content'] = 'Som <span class="comptador">' . $total_subscrites . '</span> subscriptores. <div class="subs">Faltes tu!</div>';
    break;

  }
  return $block;
}


?>
